### ISSUE TITLE
Server not actually updating

### ISSUE THREAD

**Issue by smooreace** [Dateranoth/ConanExilesServerUtility#44] opened 2018-05-19 15:17 UTC
I have no idea when this started as a problem. Last time anyone was on my servers was the 11th. So Im assuming some time after that. Server restarts have been happening as they should. Restarts for updates are happening too. When prior to the server start, the check is made to update the server. Both of mine were showing "up to date" and moving on to load the server. I ran my own update batch today after finding both of my servers showing as "invalid" in the server browser. Both updated properly and are now running fine.

Not sure whats broke or missing really

**Comment by Dateranoth** [comment] 2018-05-19 15:38
So, showing up to date, but they actually were an older version?

Did the servers actually ever restart? If so steamcmd should have ran before the server started even if it was. Now, mods will only update if they find a new version. Do you mind sending me your utility logs from the servers?

dateranoth@hotmail.com

**Comment by Doorstop2** [comment] 2018-05-19 15:50
Its using the wrong folder i had the same issue see i used the very early version of this utility in early alpha days now for some reason the old dir was still being created the dir i set in the cfg was wrong when steamcmd would update but the launching part was using the correct folder. 

So my server was suppose to be in c:\Games\conan exiles\vendor\server 
but instead when it was updating only game updates not mods they seem to install correct

it was creating a folder in c:\Games\Conan 
that was the folder it was updating so now when i ran it to check for updates it was saying it was **already updated** till i figured out that this was the problem so i switched the dir in the cfg to that one since it likes that dir and it worked server started and it was updated including mods. 

keep in mind my log looks like this not sure why this is happening 

 **Something went wrong retrieving Latest Version**
Checking for Mod Updates
Update Check Starting.
 **Something went wrong retrieving Latest Version**
Checking for Mod Updates

mod updates seem to be working not sure about game updates

**Comment by Dateranoth** [comment] 2018-05-19 16:01
Doorstop2, if you want to send me your logs I can take a look at them too. 

Also, could you both remove personal details and send me your Utility INI so I can reproduce the problems?

I have a feeling something in the INI didn’t update after one of the utility updates. 

My first thought would be for you to delete the INI and let the utility create a new one. I’ve made a lot of changes lately though so I will see if I can find the problem. 

Thanks for the input guys.

**Comment by Doorstop2** [comment] 2018-05-19 16:20
alright sent to your email the dirs in the ini is the new ones i set but you will see in the older logs i had another dir which was supposed to stay the same  also its 64bit

**Comment by Dateranoth** [comment] 2018-05-19 16:42
Ok, I think I see what's going on. SteamCMD doesn't like the spaces in the old directory. Let me see if I can quote the directory so this isn't a problem.

**Comment by Doorstop2** [comment] 2018-05-19 17:51
oh? really so is this new dir working correct like will the server auto-update correct now? 

and is this message **Something went wrong retrieving Latest Version** 
normal?

**Comment by Dateranoth** [comment] 2018-05-19 17:53
No, it's still not going to auto update correctly because of the spaces in the steamcmd dir. I'm working on the fix right now. Should have a release out in about an hour. I have the changes made, but I'm running tests to make sure they work.

**Comment by Doorstop2** [comment] 2018-05-19 17:57
oh ok thanks 👍 

appreciate it.

**Comment by Dateranoth** [comment] 2018-05-19 18:52
@Doorstop2 
Your problem should be remedied in [V3.2.1](https://github.com/Dateranoth/ConanExilesServerUtility/releases/tag/3.2.1)

Please download the latest version and give it a shot. You should be able to return to the directory structure you desire. 

@smooreace 
I still need some more information for yours.  You might start by deleting the appmanifest_443030.acf file from your Conan server directory and allowing it to be downloaded completely again.  Also, do you share your SteamCMD folder with multiple servers? If so, you might try using individual directories for each server. It shouldn't be a problem using the same folder, but I have seen caching issues before.

**Comment by Doorstop2** [comment] 2018-05-19 18:57
ok thanks will do.

**Comment by Doorstop2** [comment] 2018-05-19 19:38
Ok i think its fixed

Update Check Starting.
Server is Up to Date. Version: 2783891
Checking for Mod Updates

no longer getting the something went wrong error

**Comment by Dateranoth** [comment] 2018-05-19 19:43
Great. That bug has to have been around from the beginning. Surprising no one else has used spaces in directories. Thanks for bringing it to my attention, and I’m glad it’s working for you. 

Hopefully it will properly grab the next real update as well.

**Comment by Doorstop2** [comment] 2018-05-19 19:48
Np man.

It does seem to be working correctly now will see next update 😄

**Comment by smooreace** [comment] 2018-05-19 20:27
Sorry for the delay, Ive been building a transmission all day. I can send you all of that. Where should I send it?

I use separate steamcmd files for each server. A habit I got into years ago! 

Yes... steamcmd is opening prior to the server starting. And yes, it is restarting every day. I even tried CTRL-Cing the servers to allow the script to take over and restart... steamcmd pops up to update... file is already up to date, and the server starts.

**Comment by smooreace** [comment] 2018-05-19 20:36
And no... both servers are totally independant of each other. 

Here is the log from one server. They both basically look the same. The mod update worked fine... Its Pippi. 
https://pastebin.com/0iNB2TGR

**Comment by smooreace** [comment] 2018-05-19 20:42
Again.. both servers are nearly identical.... but here is one ini file

https://pastebin.com/Ns28Zijm

**Comment by Dateranoth** [comment] 2018-05-19 22:51
@smoorace
Ok, it looks like you have the same problem Doorstop was having. You have spaces in your path. 

It’s odd that it use to work for you. Maybe something changed with steamcmd?

If you are seeing this: 
Something went wrong retrieving Latest Version

the update check isn’t working properly. 

Anyhow, download the latest version, and it should work. It probably has installed a separate server in C:\Games. When you update the utility it will install in the proper path. 

To be sure it’s working look for the line Game is Up to Date: Version# in the logs or Game is out of date if it is. 

Sorry for the trouble.

**Comment by smooreace** [comment] 2018-05-20 00:25
Funny... kinda

It created a folder on C:    Game_Servers

And in is is a complete steamcmd install. But thats all. 33.9MB total size

**Comment by smooreace** [comment] 2018-05-20 00:26
And I havent done anything to the Conan servers in months other than add your script and one update prior to todays script update.

**Comment by Dateranoth** [comment] 2018-05-20 01:08
Yeah.  Very odd. I’m thinking that for some reason, Steam CMD stopped liking directory names with spaces without quotes.  

Let me know if the latest version works properly for you.

**Comment by Dateranoth** [comment] 2018-05-25 18:38
I’m assuming this is working now as I have had no other reports. Closing. Start a new one if the problem returns.

**Closed as completed by Dateranoth** 2018-05-25 18:38 UTC
Labels: bug
